-- MySQL Script generated by MySQL Workbench
-- Thu Dec 14 17:42:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema idocs_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema idocs_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS idocs_db DEFAULT CHARACTER SET utf8 ;
USE idocs_db ;

-- -----------------------------------------------------
-- Table companies
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS companies (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  fullname VARCHAR(255) NULL,
  cnpj VARCHAR(255) NULL,
  address TEXT NULL,
  phone VARCHAR(255) NULL,
  email VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table sectors
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS sectors (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  abbreviation VARCHAR(40) NULL,
  companies_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX fk_sectors_companies_idx (companies_id ASC) ,
  CONSTRAINT fk_sectors_companies
    FOREIGN KEY (companies_id)
    REFERENCES companies (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table users
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  avatar VARCHAR(255) NULL,
  sectors_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX fk_users_sectors1_idx (sectors_id ASC) ,
  UNIQUE INDEX email_UNIQUE (email ASC) ,
  CONSTRAINT fk_users_sectors1
    FOREIGN KEY (sectors_id)
    REFERENCES sectors (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table docs_types
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS docs_types (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  companies_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NULL,
  type VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX fk_docs_types_companies1_idx (companies_id ASC) ,
  CONSTRAINT fk_docs_types_companies1
    FOREIGN KEY (companies_id)
    REFERENCES companies (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table docs_status
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS docs_status (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NULL,
  class_color VARCHAR(255) NULL,
  companies_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX fk_docs_status_companies1_idx (companies_id ASC) ,
  CONSTRAINT fk_docs_status_companies1
    FOREIGN KEY (companies_id)
    REFERENCES companies (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table docs
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS docs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  number VARCHAR(255) NULL,
  users_id INT UNSIGNED NOT NULL,
  docs_types_id INT UNSIGNED NOT NULL,
  docs_status_id INT UNSIGNED NOT NULL,
  addressee VARCHAR(255) NULL,
  company VARCHAR(255) NULL,
  address VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX fk_docs_users1_idx (users_id ASC) ,
  INDEX fk_docs_docs_types1_idx (docs_types_id ASC) ,
  INDEX fk_docs_docs_status1_idx (docs_status_id ASC) ,
  CONSTRAINT fk_docs_users1
    FOREIGN KEY (users_id)
    REFERENCES users (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_docs_docs_types1
    FOREIGN KEY (docs_types_id)
    REFERENCES docs_types (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_docs_docs_status1
    FOREIGN KEY (docs_status_id)
    REFERENCES docs_status (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table docs_anexos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS docs_anexos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  docs_id INT UNSIGNED NOT NULL,
  users_id INT UNSIGNED NOT NULL,
  name VARCHAR(255) NULL,
  url VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX fk_docs_anexos_docs1_idx (docs_id ASC) ,
  INDEX fk_docs_anexos_users1_idx (users_id ASC) ,
  CONSTRAINT fk_docs_anexos_docs1
    FOREIGN KEY (docs_id)
    REFERENCES docs (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_docs_anexos_users1
    FOREIGN KEY (users_id)
    REFERENCES users (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table docs_historical
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS docs_historical (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  docs_id INT UNSIGNED NOT NULL,
  docs_status_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX fk_docs_historical_docs1_idx (docs_id ASC) ,
  INDEX fk_docs_historical_docs_status1_idx (docs_status_id ASC) ,
  CONSTRAINT fk_docs_historical_docs1
    FOREIGN KEY (docs_id)
    REFERENCES docs (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_docs_historical_docs_status1
    FOREIGN KEY (docs_status_id)
    REFERENCES docs_status (id)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;